export const FETCH_GALLERY = 'FETCH_GALLERY';

export const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';

export const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

export const ADD_PHOTO = 'ADD_PHOTO';

export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS';

export const ADD_PHOTO_FAILURE = 'ADD_PHOTO_FAILURE';
